export const RECENTLY_VISITED_SHARED_RESOURCES =
  "RECENTLY_VISITED_SHARED_RESOURCES";
export const RECENTLY_VISITED_DOCUMENTS = "RECENTLY_VISITED_DOCUMENTS";
export const RECENTLY_VISITED_DEVICES = "RECENTLY_VISITED_DEVICES";
export const RECENTLY_VISITED_ASSETS = "RECENTLY_VISITED_ASSETS";
export const RECENTLY_VISITED_DASHBOARDS = "RECENTLY_VISITED_DASHBOARDS";
export const RECENTLY_VISITED_COMMUNITY_STREAMS =
  "RECENTLY_VISITED_COMMUNITY_STREAMS";
export const RECENTLY_VISITED_PROJECTS = "RECENTLY_VISITED_PROJECTS";
export const RECENTLY_VISITED_STREAMS = "RECENTLY_VISITED_STREAMS";
